# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.IntegerField(choices=[(0, 'Wrong Answer'), (1, 'Accepted'), (2, 'Runtime Error'), (3, 'Server Error'), (4, 'Timed Out')]),
        ),
    ]
