# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0002_auto_20171010_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='case',
            name='sample_case',
            field=models.BooleanField(default=False),
        ),
    ]
