# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinejudge', '0004_auto_20171012_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(20, 'Easy'), (40, 'Medium'), (70, 'Hard')]),
        ),
    ]
